name: Victoria Roe
favicon: null
layout_spectrum: 0.50482
typography_spectrum: 0.85275106318295
title: Victoria Roe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#2d4021'
    - '#898887'
    - '#f654fa'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
